#!/usr/bin/env bash
# Check if an argument (IP address) is passed
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Store the IP address argument
IP_ADDRESS="$1"

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
