#!/usr/bin/env bash
# Script that changes the IP

# Backup the current /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Remove the line containing '127.0.0.1 localhost' from /etc/hosts
sudo sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts

# Add '127.0.0.2 localhost' to /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Add '8.8.8.8 facebook.com' to /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts