#!/usr/bin/env bash
#Script that change the IP

sudo cp /etc/hosts /etc/hosts.bak
read -p "Enter new IP address for localhost: " new_localhost_ip
read -p "Enter new IP address for facebook.com: " new_facebook_ip
{
    echo "$new_localhost_ip       localhost"
    echo "$new_facebook_ip         facebook.com"
} | sudo tee /etc/hosts > /dev/null
